// <auto-generated />
using CsharpORM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CsharpORM.ApiService.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    [Migration("20250313132205_NomeDaMigration")]
    partial class NomeDaMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CsharpORM.ApiService.Classes.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "123.456.789-00",
                            Nome = "João da Silva"
                        },
                        new
                        {
                            Id = 2,
                            Cpf = "987.654.321-00",
                            Nome = "Maria Oliveira"
                        });
                });

            modelBuilder.Entity("CsharpORM.ApiService.Classes.Emprestimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("Parcelas")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxaJuros")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Emprestimos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            Parcelas = 12,
                            TaxaJuros = 2.5m,
                            Valor = 1000.00m
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 1,
                            Parcelas = 24,
                            TaxaJuros = 3.0m,
                            Valor = 5000.00m
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 2,
                            Parcelas = 10,
                            TaxaJuros = 1.8m,
                            Valor = 2000.00m
                        });
                });

            modelBuilder.Entity("CsharpORM.ApiService.Classes.Emprestimo", b =>
                {
                    b.HasOne("CsharpORM.ApiService.Classes.Cliente", "Cliente")
                        .WithMany("Emprestimos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CsharpORM.ApiService.Classes.Cliente", b =>
                {
                    b.Navigation("Emprestimos");
                });
#pragma warning restore 612, 618
        }
    }
}
